Repository FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-backend, pull requests merged in 2023-06, with the labels that each got.

#59 Develop #58 fix db and picture
  src/main/java/at/fh/joanneum/irfc/model/VotingResult/VotingResultDTO.java
  src/main/java/at/fh/joanneum/irfc/model/event/EventDTO.java
  src/main/java/at/fh/joanneum/irfc/model/vote/VoteDTO.java
  src/main/java/at/fh/joanneum/irfc/model/voting/VotingDTO.java
  src/main/java/at/fh/joanneum/irfc/model/votingPartialResult/VotingPartialResultDTO.java
  src/main/java/at/fh/joanneum/irfc/model/votingPartialResult/VotingPartialResultMapper.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/EventEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VoteEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VotingEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VotingPartialResultEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VotingResultEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/EventRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/VoteRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/VotingRepository.java
  src/main/java/at/fh/joanneum/irfc/rest/EventInfoApi.java
  src/main/java/at/fh/joanneum/irfc/rest/EventLocationApi.java
  src/main/java/at/fh/joanneum/irfc/rest/PictureApi.java
  src/main/java/at/fh/joanneum/irfc/rest/VotingApi.java
  src/main/java/at/fh/joanneum/irfc/rest/VotingResultApi.java
  src/main/java/at/fh/joanneum/irfc/service/EventInfoService.java
  src/main/java/at/fh/joanneum/irfc/service/EventService.java
  src/main/java/at/fh/joanneum/irfc/service/PictureService.java
  src/main/java/at/fh/joanneum/irfc/service/VoteService.java
  src/main/java/at/fh/joanneum/irfc/service/VotingPartialResultService.java
  src/main/java/at/fh/joanneum/irfc/service/VotingResultService.java
  src/main/java/at/fh/joanneum/irfc/service/VotingService.java
  src/main/resources/application.yml
  src/main/resources/db/15-create-voting-table.xml
  src/main/resources/db/20-create-vote-table.xml
  src/main/resources/db/32-create-voting-result-table.xml
  src/main/resources/db/53-add-fields.xml
  src/main/resources/db/changeLog.xml
Labels: Backend

#64 fixed vote dto
  src/main/java/at/fh/joanneum/irfc/model/vote/VoteDTO.java
  src/main/java/at/fh/joanneum/irfc/service/VoteService.java
Labels: Backend

#66 #64 add constrains for table event
  src/main/java/at/fh/joanneum/irfc/model/event/EventDTO.java
  src/main/java/at/fh/joanneum/irfc/model/event/EventMapper.java
  src/main/java/at/fh/joanneum/irfc/model/eventCategory/EventCategoryDTO.java
  src/main/java/at/fh/joanneum/irfc/model/eventCategory/EventCategoryMapper.java
  src/main/java/at/fh/joanneum/irfc/model/eventInfo/EventInfoDTO.java
  src/main/java/at/fh/joanneum/irfc/model/vote/VoteDTO.java
  src/main/java/at/fh/joanneum/irfc/model/vote/VoteMapper.java
  src/main/java/at/fh/joanneum/irfc/model/voting/VotingDTO.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/EventCategoryEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/EventEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/EventInfoEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/PictureEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VoteEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VotingEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VotingPartialResultEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VotingResultEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/EventInfoRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/EventRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/PictureRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/VoteRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/VotingPartialResultRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/VotingRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/VotingResultRepository.java
  src/main/java/at/fh/joanneum/irfc/rest/EventApi.java
  src/main/java/at/fh/joanneum/irfc/rest/EventCategoryApi.java
  src/main/java/at/fh/joanneum/irfc/rest/EventInfoApi.java
  src/main/java/at/fh/joanneum/irfc/rest/EventLocationApi.java
  src/main/java/at/fh/joanneum/irfc/rest/PictureApi.java
  src/main/java/at/fh/joanneum/irfc/rest/VoteApi.java
  src/main/java/at/fh/joanneum/irfc/rest/VotingApi.java
  src/main/java/at/fh/joanneum/irfc/rest/VotingResultApi.java
  src/main/java/at/fh/joanneum/irfc/service/EventCategoryService.java
  src/main/java/at/fh/joanneum/irfc/service/EventInfoService.java
  src/main/java/at/fh/joanneum/irfc/service/EventLocationService.java
  src/main/java/at/fh/joanneum/irfc/service/EventService.java
  src/main/java/at/fh/joanneum/irfc/service/PictureService.java
  src/main/java/at/fh/joanneum/irfc/service/VoteService.java
  src/main/java/at/fh/joanneum/irfc/service/VotingPartialResultService.java
  src/main/java/at/fh/joanneum/irfc/service/VotingResultService.java
  src/main/java/at/fh/joanneum/irfc/service/VotingService.java
  src/main/resources/db/64-add-event-table-constrains.xml
  src/main/resources/db/changeLog.xml
Labels: bug

#68 fixed update
  src/main/java/at/fh/joanneum/irfc/persistence/repository/EventRepository.java
  src/main/java/at/fh/joanneum/irfc/service/EventService.java
Labels: bug, Backend

#69 fixed query
  pom.xml
  src/main/java/at/fh/joanneum/irfc/persistence/repository/EventRepository.java
Labels: bug, Backend

#71 fixed voting deletion
  pom.xml
  src/main/java/at/fh/joanneum/irfc/model/votingPartialResult/VotingPartialResultDTO.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VotingEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/entiy/VotingResultEntity.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/EventInfoRepository.java
  src/main/java/at/fh/joanneum/irfc/persistence/repository/VotingResultRepository.java
  src/main/java/at/fh/joanneum/irfc/service/EventInfoService.java
  src/main/java/at/fh/joanneum/irfc/service/VotingResultService.java
  src/main/java/at/fh/joanneum/irfc/service/VotingService.java
  src/main/resources/db/64-fixed-voting-result-fk.xml
  src/main/resources/db/changeLog.xml
Labels: bug, Backend
